"""add_user_id_to_proposals

Revision ID: f2edb5b20f45
Revises: be2049cbf0b1
Create Date: 2026-06-01 08:40:15.800055

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2edb5b20f45'
down_revision: Union[str, None] = 'be2049cbf0b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposals', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_proposals_user_id'), 'proposals', ['user_id'], unique=False)
    op.create_foreign_key('fk_proposals_user_id_users', 'proposals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_proposals_user_id_users', 'proposals', type_='foreignkey')
    op.drop_index(op.f('ix_proposals_user_id'), table_name='proposals')
    op.drop_column('proposals', 'user_id')
    # ### end Alembic commands ###
